### ISSUE TITLE
Module for serial sections

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#2]
Hi Benjamin, SBEMimage looks quite nice and easy to use, congratulations.

I would still be interested in adding a small module to allow users to acquire imagery from serial sections collected on flat substrates. I assume that SBEMimage is now stable enough to try it ? Would you maybe be able to show briefly a starting point where you think that such a capability would fit ?

In the most basic implementation, the starting point would be text files containing 
- stage calibration landmarks
- centers and angles of the mosaics to acquire
After a brief landmark calibration, the centers and angles of the mosaics would then be known in the stage coordinates and the imaging could start. 

Thanks a lot

**Comment by btitze** [comment]
Hi Thomas,

thanks for getting in touch! I remember our conversation from last year about this.
Let's talk about how this functionality could be integrated. I'll send you an e-mail tomorrow.
