### ISSUE TITLE
more user-friendly way to change the rotation of a grid ?

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#20]
It can currently be done in the grid settings menu, but lacks user friendliness. 

Suggestions mentioned in discussion: 
- rightclick on a grid -> change rotation -> a slider pops up with also numerical entry and arrows ?

- press a key and adjust with the mouse wheel (maybe too slow or not precise enough) ?

-  a grid could always display a small anchor that can be grabbed for rotation (probably the most user-friendly) ?
![image](https://user-images.githubusercontent.com/34257249/63105876-f72b3080-bf81-11e9-8381-e9eb159d04fd.png)

**Comment by btitze** [comment]
I've implemented a dialog with a slider yesterday. The advantage of the dialog is that there is also a numerical display in a spinbox, and the user can enter a precise value in that spinbox. The buttons OK and Cancel allow the user to either keep the new rotation or to discard it.

I agree that the most user-friendly approach would be to include an anchor, or small curved arrows around the corners (as in Adobe Illustrator). I could implement that later.
