### ISSUE TITLE
magc: possible to use existing autofocus dialog ?

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#24]
Currently each of the many grids contains only one tile, which is also the reference tile for autofocus.
When starting an acquisition, the software correctly loops through the acquisition for all grids, but autofocus is always omitted. I used the tracking mode "track selected, approx. others".

I have set interval N to 1, hoping that magc mode would be seen as having only slice 0, which I thought would have triggered autofocus, but no. Is there a way to activate AF in magc mode without changing much the dialog ?

Also, I would need to change the autostig interval to make it depend on grids instead of slices, correct ?

Also, the max permitted WD/astig changes are computed from one autofocused tile to the next autofocused tile ? This probably would not require a change then.

Thanks for any input @btitze 

![whatAutofocusParametersApplicableToMagC](https://user-images.githubusercontent.com/34257249/64813330-67d56500-d5a1-11e9-86ad-b501525c2dfb.png)

**Comment by btitze** [comment]
The SmartSEM autofocus is never called on the very first slice. I thought that this default setting makes sense because a user would always start a stack after focusing the beam.
But in your case, the autofocus must be active on slice 0.
I've pushed a few changes to your branch that should make it work. When MagC mode is active, autofocus and autostigmator will be active on slice 0 (the only slice). For now, the choice of SmartSEM autofocus and 'Track selected, approx. others' will be enforced for MagC. All settings in the dialog that are not applicable to MagC are disabled. We need to discuss how to adapt the autostig delay.

**Comment by templiert** [comment]
> The SmartSEM autofocus is never called on the very first slice. I thought that this default setting makes sense because a user would always start a stack after focusing the beam.
But in your case, the autofocus must be active on slice 0.
I've pushed a few changes to your branch that should make it work. When MagC mode is active, autofocus and autostigmator will be active on slice 0 (the only slice). For now, the choice of SmartSEM autofocus and 'Track selected, approx. others' will be enforced for MagC. All settings in the dialog that are not applicable to MagC are disabled.

Thanks @btitze, about to test it.

> We need to discuss how to adapt the autostig delay.

There could be an autostig delay that depends on grids instead of slices, i.e., do autostig every 5 grids. 

The autostig would be performed on the tiles that are defined as autofocus ref tiles. In this case the user could chose between doing an {autofocus-autostig-autofocus} sequence or a merged autofocus/autostig. This choice would be experiment-wide, no need to define that for every grid.

If there is no autofocus tile in a grid, then there will be no autostig even if autostig is activated for this grid (I doubt that a user would want to make an autostig without doing an autofocus).

**Comment by templiert** [comment]
> There could be an autostig delay that depends on grids instead of slices, i.e., do autostig every 5 grids.

Implemented in [this commit](https://github.com/SBEMimage/SBEMimage/commit/e51b15e7df3f5eb60b2c7e3f7c4ba7a9a6d074eb). 

The stig interval is very basic for now. It simply checks the remainder of `grid_number % autostig_interval`. It will need to be adapted when the grid acquisition flag is implemented. Then instead of checking the remainder of the absolute grid_number, it should check the remainder of something like `grid_number_acquired`
