### ISSUE TITLE
magc: fail to propagate autofocus reference tile to other grids

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#25]
For example all grids have 2x2 tiles and tile 0.3 is set as autofocus reference.

I am trying to propagate the properties of Grid 0 to all others. It works for all properties except for which tiles are set as autofocus reference.

To set the autofocus reference tile to other grids I 
- am editing the `self.cfg['autofocus']['ref_tiles']` list
- am updating the viewport with `viewport.mv_draw()`

, but 

- the 'AUTOFOCUS' label does not appear in the viewport on the tiles that should have been updated (it gets updated only with manual right click -> set tile as ref autofocus)
- right-clicking on a tile that should have been updated shows that it has indeed not been set as autofocus reference
- I see that the current `self.cfg['autofocus']['ref_tiles']` list contains all ref tiles, e.g. ['0.3', '1.3', '2.3', '3.3', ...] but viewport.mv_draw() does not draw the autofocus label and does not update the ref tile in the right click context menu
.

Am I forgetting to update something ? I'm updating the [cfg here](https://github.com/SBEMimage/SBEMimage/blob/magc-integration/src/grid_manager.py#L165-L190):
```
        # --- setting the autofocus reference tiles ---
        ref_tile_list = json.loads(self.cfg['autofocus']['ref_tiles'])
        # get ref tiles from source
        source_ref_tiles = []
        for tile_key in ref_tile_list:
            grid, tile = tile_key.split('.')
            grid, tile = int(grid), int(tile)
            if grid == s:
                source_ref_tiles.append(tile)
        print('source', s, 'source_ref_tiles', source_ref_tiles, 'ref_tile_list', ref_tile_list)
        # remove ref tiles from target
        ref_tile_list = [key for key in ref_tile_list if
            int(key.split('.')[0]) != t]
        
        # add source ref tiles to target
        for source_ref_tile in source_ref_tiles:
            ref_tile_list.append(str(t) + '.' + str(source_ref_tile))

        # sort the tile list
        ref_tile_list.sort()
        
        # save the new tile list
        self.cfg['autofocus']['ref_tiles'] = json.dumps(ref_tile_list)
```
and updating viewport at the end of the propagation to all sections [here](https://github.com/SBEMimage/SBEMimage/blob/magc-integration/src/viewport.py#L2034):

```
    def mv_propagate_grid_all_sections(self):
        clicked_section_number = self.selected_grid
        section_number = self.gm.get_number_grids()
        for section in range(section_number):
            self.gm.propagate_source_grid_to_target_grid(clicked_section_number,
            section)
        self.mv_draw()
```

**Comment by btitze** [comment]
This all looks fine, but the changed ref_tile_list is not reloaded in the autofocus module.

I think the only thing you need to change is the following:
Instead of writing the new tile list directly to the self.cfg[][] as you do here:
`# save the new tile list`
`self.cfg['autofocus']['ref_tiles']` = json.dumps(ref_tile_list)`
Do this:
`# save the new tile list`
`self.af.set_ref_tiles(ref_tile_list)`

**Comment by templiert** [comment]
Ok thanks, yes it's working.
