### ISSUE TITLE
magc: flag for acquisition of grids

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#27]
The section list in magc allows the user to select custom sets of sections and is used to determine which sections will be acquired in an acquisition session. Sections (i.e. grids) that will be acquired are the ones that are checked in the list. What would be the easiest way to implement such a grid flag ?

This flag should be stronger than the tile activation flag, i.e., all tiles of an unchecked grid will be skipped even if some tiles are activated.

A simple check like:
```
for grid_number in range(number_grids):
    if grid_number in checked_sections: 
```
at the beginning of the [grid acquisition loop](https://github.com/SBEMimage/SBEMimage/blob/master/src/stack_acquisition.py#L767-L797) seems to be an easy way to do it ? Does it disrupt other things that I am missing ? 

![image](https://user-images.githubusercontent.com/34257249/64862724-88e69600-d633-11e9-8b4f-ec910739c58f.png)

**Comment by btitze** [comment]
This should be straightforward. Such a feature is useful, also for overviews. I'll think about the best way to do it and will push it to the master soon.
