### ISSUE TITLE
Add "pip install pyserial" in installation doc ?

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#3]
Windows 10, Anaconda

Neither `pip install win32com` nor `pip install pythoncom` worked:

`$ pip install win32com
Collecting win32com
  Could not find a version that satisfies the requirement win32com (from versions: )
No matching distribution found for win32com
(py36)

$ pip install pythoncom
Collecting pythoncom
  Could not find a version that satisfies the requirement pythoncom (from versions: )
No matching distribution found for pythoncom
`

I tried to start sbemimage.py anyway and got:

`Traceback (most recent call last):
  File "SBEMimage.py", line 26, in <module>
    from main_controls import MainControls
  File "C:\pytools\SBEMimage\src\main_controls.py", line 39, in <module>
    from plasma_cleaner import PlasmaCleaner
  File "C:\pytools\SBEMimage\src\plasma_cleaner.py", line 17, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'`

Then `pip install pyserial` and start was successful.  Was the "serial" from pywin32 or does pythoncom or win32com have another "serial" package ?

**Comment by btitze** [comment]
Thanks for pointing this out. 
I will include "pip install pywin32" in the next version of the manual. It appears to include both win32com and pythoncom.

The module "serial" that can be imported in Python with "import serial" is actually called "pyserial", so you would have to use "pip install pyserial". (http://pyserial.readthedocs.io/en/latest/pyserial.html#installation)
I thought pyserial was already included in Anaconda...
I will also add this in the manual.

**Comment by templiert** [comment]
Thanks. Sorry, it was actually pip install pyserial that worked (just edited).

**Comment by btitze** [comment]
I've now included the file requirements.txt, which lists all required packages.
