### ISSUE TITLE
in grid setting dialog, rotate around center or around tile 0

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#39]
I believe there is a small inconsistency about grid rotation: in the viewport dialog, the default is rotation around the center of the grid (as opposed to around the center of tile 0), while in the grid dialog, there is no choice and by default the rotation center is the center of tile 0.
[In this commit in magc-dev](https://github.com/SBEMimage/SBEMimage/commit/cbcd70dcc2ddca4908086c3bc2d4941c0a6f5dce) I am setting the default in the grid dialog to rotation center = grid center.
I am mentioning it here because I am not sure whether you may want this outside of magc too.

**Comment by btitze** [comment]
I agree, good suggestion - rotating around the centre is more intuitive. Let's make that the default in the grid dialog. So you can take out the 'if not self.magc_mode:' part.
