### ISSUE TITLE
Installing needed modules

### ISSUE THREAD

**Issue by cwood1967** [SBEMimage/SBEMimage#41]
Your documentation pdf file gives directions to use pip to install win32com and pythoncom. Neither of these are found when using pip:

```
S:\micro\internal\cjw\SBEMimage>pip install win32com
ERROR: Could not find a version that satisfies the requirement win32com (from versions: none)
ERROR: No matching distribution found for win32com

 S:\micro\internal\cjw\SBEMimage>pip install pythoncom
ERROR: Could not find a version that satisfies the requirement pythoncom (from versions: none)
ERROR: No matching distribution found for pythoncom
```

Just installing pywin32 seems to install both win32com and pythoncom, and your requirements.txt file only lists win32 as needed.

Can the documentation be updated to reflect this.

**Comment by btitze** [comment]
Thank you for pointing this out. I've removed the obsolete pip install instructions and included 'pip install -r requirements.txt'.

The short pdf guide will soon (hopefully in July as part of a new release) be replaced with a more detailed user guide, which will be hosted on https://readthedocs.org/
