### ISSUE TITLE
Focus tool: autofocus functionality and logarithmic step size

### ISSUE THREAD

**Issue by ghost** [SBEMimage/SBEMimage#53]
To make it a more streamlined process, the Focus tool needs to work in a fully automated way without need to look at the microscope.
On the Zeiss Sigma, running the AF/Stig tool in DM sort of works but is really slow, and the SmartSEM version on it’s own also sort of works to get a starting point for a new sample, but it would be much nicer to have it integrated.
Move SEM auto-focus into Focus tool.
The current step size (slider on the right side) is not large enough for a Sigma which makes the process very painful. The steps can be changed to logarithmic ones.

**Comment by btitze** [comment]
The autofocus functionality for the focus tool is now implemented in 'dev', soon to be merged to master. 
The slider now outputs a a value according to the formula: x^2 + 1. If you move it towards 'coarse', the steps will now be much larger.
