### ISSUE TITLE
Focus tool acquisition freeze (Zeiss Sigma)

### ISSUE THREAD

**Issue by ghost** [SBEMimage/SBEMimage#57]
In Focus tool, selecting a small pixel size (e.g. 6) and a long dwell time (e.g. 6.4) and 'Start'-ing causes SBEMimage to wait infinitely for a scan that never happens or completes.

SmartSEM behaviour:
- Unfreeze
- Freeze or unfreeze button highlighted
- Completely black capture screen
- Unresponsive (stuck), until changing resolution

**Comment by btitze** [comment]
I could not reproduce this on the Zeiss GeminiSEM and Merlin, but perhaps recent changes have made this bug report obsolete. Please file a new bug report if the above problems still happen when running the most recent code in 'dev'.
