### ISSUE TITLE
Mock SEM that takes images from a previous SBEMimage acquisition

### ISSUE THREAD

**Issue by K-Meech** [SBEMimage/SBEMimage#76]
For developing tools that are specific to EM images of a particular sample/type, it would be very useful to have a mock SEM that could take images from a previous SBEMimage acquisition. e.g. When the overview id / grid id / slice number match, it would take images from another SBEMimage folder, rather than generating random images.

This is useful for e.g. the targeting stuff I'm working on where I need to simulate acquiring EM images of a sample that also has x-ray/light microscopy data.

I have something hacked together locally that works for this, but it would be nice to generalise it, if it was useful? @btitze - maybe we can discuss this in the zoom meeting, if you think it would be of general use?

**Comment by btitze** [comment]
That's a great idea! A "stack replay" mode for the mocks. Sure, let's discuss this in the planned zoom meeting!
