### ISSUE TITLE
Error on fresh SBEMimage installation with latest scikit-image

### ISSUE THREAD

**Issue by K-Meech** [SBEMimage/SBEMimage#87]
The latest scikit-image version has removed the function ```skimage.feature.register_translation``` leading to errors on a fresh sbemimage installation. This needs to be replaced with another function, or add skimage <0.19.0 to the requirements.

**Comment by btitze** [comment]
I've replaced `skimage.feature.register_translation` in the 'dev' branch. On 'master', I added the version restriction <0.19.0 for scikit-image, which will be removed again when we merge 'dev' for the next release.
